### ISSUE TITLE
Debian bullseye

### ISSUE THREAD

**Issue by AaronDewes** [getumbrel/umbrel-os#159]
Debian bullseye launches in summer this year, and we should update to that release when RPi OS Bullseye is released (Docker base images and Umbrel OS). I've created this issue to track all the required changes and progress on that update.

- [ ] Update docker base images
- [ ] Update Umbrel OS to build bullseye
- [ ] Create distro update backend
- [ ] Create distro update frontend

I'm not sure how you want to implement that (Ship it as part of an OTA update/Extra update button just for OTA updates).

@lukechilds @mayankchhabra @louneskmt What do you think about this?

**Comment by j4Hu** [comment]
hi, maybe it should be 64bit version of OS, because of performance.

"Across the few dozen different workloads tested, switching Raspberry Pi OS 11 for the 64-bit version improved the performance on average by about 48%. See all the 32-bit vs. 64-bit Raspberry Pi benchmarks over on OpenBenchmarking.org."

https://www.phoronix.com/scan.php?page=article&item=raspberrypi-32bit-64bit&num=4
